create database walmartsales;

use walmartsales;

CREATE TABLE IF NOT EXISTS sales(
	invoice_id VARCHAR(30) NOT NULL PRIMARY KEY,
    branch VARCHAR(5) NOT NULL,
    city VARCHAR(30) NOT NULL,
    customer_type VARCHAR(30) NOT NULL,
    gender VARCHAR(30) NOT NULL,
    product_line VARCHAR(100) NOT NULL,
    unit_price DECIMAL(10,2) NOT NULL,
    quantity INT NOT NULL,
    tax FLOAT(6,4) NOT NULL,
    total DECIMAL(12, 4) NOT NULL,
    date DATETIME NOT NULL,
    time TIME NOT NULL,
    payment_method VARCHAR(15) NOT NULL,
    goods_sold DECIMAL(10,2) NOT NULL,
    gross_margin_pct FLOAT(11,9),
    gross_income DECIMAL(12, 4),
    rating FLOAT(2, 1)
);
select * from sales;


--  -----------------------------------------------------------------------------------------
-- ------------------------------Feature Egineering ----------------------------------------

-- Time of day

select
     time,
(case 
	when time  between "00:00:00" and "12:00:00" then "Morning"
    when time between "12:01:00" and "16:00:00" then "Afternoon"
    Else "Evening"
    end
) as time_of_day
 from sales;
 
alter table sales add column time_of_day varchar(50);

update sales
set time_of_day = case 
	when time  between "00:00:00" and "12:00:00" then "Morning"
    when time between "12:01:00" and "16:00:00" then "Afternoon"
    Else "Evening"
    end;
    
-- day_name
select date,
       dayname(date) as day_name
       from sales;
       
alter table sales add column day_name varchar(20);

update sales
set day_name =   dayname(date);     


-- month_name
select date, monthname(date) as month_name from sales;

alter table sales add column month_name varchar(10);

update sales
set month_name = monthname(date);

-- Questions

-- Generic Question

-- How many unique cities does the data have?

select distinct(city) 
from sales;

-- In which city is each branch?
select distinct(city), branch
from sales;

use walmartsales;
-- ------------------------------------------------------------------------------------------
-- -------------------- Sales Performance ---------------------------------------------------

-- Number of sales made in each time of the day per weekday?
select time_of_day,
        count(*) as total_sales
        from sales 
        where day_name = "sunday"
        group by time_of_day
        order by total_sales desc;
 
 -- Which of the customer types brings the most revenue?
select customer_type,
       sum(total) as most_revenue
       from sales
       group by customer_type 
       order by most_revenue desc;
       
-- Which city has the largest tax percent/ VAT (Value Added Tax)?
select city,
       max(tax) as largest_tax
       from sales
       group by city
       order by largest_tax desc;
       
-- Which customer type pays the most in VAT?
select customer_type,
        sum(tax) as most_vat
        from sales
        group by customer_type
        order by most_vat desc;

--  What is the total revenue generated by each branch?
SELECT Branch, SUM(Total) AS TotalRevenue
FROM sales
GROUP BY Branch
ORDER BY TotalRevenue DESC;

-- Which product category generates the highest revenue?
SELECT Product_line, SUM(Total) AS TotalRevenue
FROM sales
GROUP BY Product_line
ORDER BY TotalRevenue DESC
LIMIT 1;

-- What is the average transaction value for each customer type?
SELECT Customer_Type, AVG(Total) AS AverageTransactionValue
FROM sales
GROUP BY Customer_Type;

-- What is the sales trend over time?
SELECT DATE(Date) AS SaleDate, SUM(Total) AS TotalSales
FROM sales
GROUP BY SaleDate
ORDER BY SaleDate;

-- Which payment method is most popular?
SELECT Payment_method, COUNT(*) AS TransactionCount
FROM sales
GROUP BY Payment_method
ORDER BY TransactionCount DESC
LIMIT 1;

-- What is the gross profit margin for each product category?
SELECT Product_line, AVG(Gross_Margin_pct) AS AverageGrossMargin
FROM sales
GROUP BY Product_line;

-- -----------------------------------------------------------------------------------
-- ------------------------- Customer Analysis ---------------------------------------

-- How many unique customer types does the data have?

select distinct(customer_type) 
       from sales;
       
-- How many unique payment methods does the data have?

select distinct(payment_method)  
from sales;

-- What is the most common customer type?
select customer_type,
         count(*) as most_common
         from sales
         group by customer_type
         order by most_common desc;
       
 -- Which customer type buys the most?
 select customer_type,
        count(*) as total_purchases
        from sales
        group by customer_type 
        order by total_purchases desc;
        
-- What is the gender of most of the customers?
select gender,
	   count(*) as Most_customers
       from sales
       group by gender
       order by most_customers desc;
       
-- What is the gender distribution per branch?
select gender,
        count(*) as gender_cnt
       from sales
       where branch = "c"
       group by gender 
       order by gender_cnt desc;
       
-- Which time of the day do customers give most ratings?
select time_of_day,
        avg(rating) most_ratings
       from sales
       group by time_of_day
       order by most_ratings desc;

-- What is the customer distribution by gender and customer type?
SELECT Gender, Customer_Type, COUNT(*) AS CustomerCount
FROM sales
GROUP BY Gender, Customer_Type;

-- Which customer type spends more on average?
SELECT Customer_Type, AVG(Total) AS AverageSpend
FROM sales
GROUP BY Customer_Type
ORDER BY AverageSpend DESC;

-- Which product category is most popular among different customer segments?
SELECT Customer_Type, Product_line, COUNT(*) AS ProductCount
FROM sales
GROUP BY Customer_Type, Product_line
ORDER BY Customer_Type, ProductCount DESC;


-- ---------------------------------------------------------------------------
-- ----------------------- Product Analysis ----------------------------------

-- How many unique product lines does the data have?
select distinct(product_line)
from sales;

-- What is the most common payment method?

select payment_method, count(payment_method) as most_use_paid
from sales
group by payment_method
order by most_use_paid desc;

-- What is the most selling product line?
select product_line,
	count(product_line) as cnt
from sales
group by product_line
order by cnt desc;

-- What is the total revenue by month?
select sum(total) as Total_revenue,
       month_name
from sales
group by month_name
order by Total_revenue desc;

-- What month had the largest COGS?

select 
       month_name,
       sum(goods_sold) as cogs
       from sales
       group by month_name
       order by cogs desc
       limit 1;
       
-- What product line had the largest revenue?
select sum(total) as LG,
       product_line
       from sales
       group by product_line
       order by LG desc
       limit 1;
       
-- What is the city with the largest revenue?
select city,
      sum(total) as Largest_revenue
      from sales
      group by city
      order by Largest_revenue desc;
      
-- What product line had the largest VAT (Tax)?
select product_line,
avg(tax) as total_vat
      from sales
      group by product_line
      order by total_vat
      limit 1;



-- Which branch sold more products than average product sold?

select branch,
       sum(quantity) as qty
       from sales
       group by branch
       having sum(quantity) > ( select avg(quantity) from sales);

-- What is the most common product line by gender?

select product_line, gender,
       count(gender) as total_count
        from sales
        group by gender,product_line
        order by total_count desc;
        

-- What is the average rating of each product line?

select avg(rating),
       product_line
       from sales
       group by product_line;

--  What is the best-selling product?
SELECT Product_line, SUM(Quantity) AS TotalQuantity
FROM sales
GROUP BY Product_line
ORDER BY TotalQuantity DESC
LIMIT 1;

-- What is the average unit price for each product category?
SELECT Product_line, AVG(Unit_Price) AS AverageUnitPrice
FROM sales
GROUP BY Product_line;

--  Which products have the highest profit margins?
SELECT Product_line, AVG(Gross_Margin_pct) AS AverageGrossMargin
FROM sales
GROUP BY Product_line
ORDER BY AverageGrossMargin DESC;

select * from sales;
use walmartsales;